# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
disqus: jakubdziworski
google_analytics:

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Jakub Dziworski
title: Jakub Dziworski
description: Jakub Dziworski's JVM dev blog
author:
  name: Jakub Dziworski
  email: jakub.dziworski@gmail.com
  github: jakubdziworski
  twitter: Jakub_Dziworski
  pinterest: kubadziworski
  linkedin: jakub-dziworski-795079105
  bio: Dev Blog
  email_md5: a90846857e328572041910f988965bbf

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
BASE_PATH: https://jakubdziworski.github.io

gems: [jekyll-paginate]
